### ISSUE TITLE
 ERROR  [worker reload] [worker init] defineEventHandler is not defined   

### ISSUE THREAD

**Issue by rrd108** [rrd108/nuxt-token-authentication#4]
installing the module and then run yarn dev results in this error

It may be coming from https://github.com/nuxt/nuxt/releases/tag/v3.8.0

**Comment by rrd108** [comment]
@danielroe I was not able to find out how to fix this

**Comment by danielroe** [comment]
Here you go!

https://github.com/rrd108/nuxt-token-authentication/pull/5
